# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ybw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='swiper',
            table='swiper',
        ),
    ]
