# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybw', '0002_auto_20190314_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'lby',
            },
        ),
    ]
