# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ybw', '0003_lby'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lby',
            new_name='Swiper1',
        ),
        migrations.AlterModelTable(
            name='swiper1',
            table='swiper1',
        ),
    ]
