# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ybw', '0007_detail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='name',
        ),
    ]
