# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybw', '0009_detail_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
    ]
