# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ybw', '0013_auto_20190315_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshop',
            name='cart',
            field=models.CharField(max_length=200),
        ),
    ]
